### ISSUE TITLE
on-run-end failed, error:  value too long for type character varying(65535)

### ISSUE THREAD

**Issue by manuel-rodriguez-sonarsource** [elementary-data/dbt-data-reliability#650]
Hi all! 👋 

While running `dbt test` we got an error saying: 

```
on-run-end failed, error:
 value too long for type character varying(65535)
```

After digging a bit, I found that the culprit is one of our unit-test for some macros, where we generate the test code using jinja to assert several conditions.
The compiled code ends up in a really long file. I found that your run-end hook calls several macros, but I got a bit lost in there. I guess that one of these macros is trying to upload the compiled code into a VARCHAR or TEXT variable (in Redshift) causing it to overflow (since the max size for a VARCHAR in Redshift is `65535`).

Some more details about my env:

I'm running on Redshift using dbt core.

```
dbt version: 1.7.4
dbt-redshift: 1.7.1
elementary dbt-package: 0.13.0
edr version: 0.13.2
```

I'm just posting the issue, so I don't want to lead to any solution before is checked that it's not just a singular thing, but an easy solution would be to [truncate](https://jinja.palletsprojects.com/en/3.1.x/templates/#jinja-filters.truncate) every string saved to the max size or the TEXT variable based on the adaptor.

**Comment by haritamar** [comment]
Hi @manuel-rodriguez-sonarsource !
Thanks a lot for opening this issue, and very sorry we are only just responding to it.

This is actually a bit surprising since we do truncate this value [here](https://github.com/elementary-data/dbt-data-reliability/blob/master/macros/utils/graph/get_compiled_code.sql#L5), where `get_column_size` returns exactly `65535` for Redshift.

In any case, since it's been a while I'll go ahead and close this issue but if still relevant please feel free to open a new issue in the [main Elementary repo](https://github.com/elementary-data/elementary/issues) (we are trying to concentrate issue management there).

Thank you!
Itamar

**Comment by DakotaMichael** [comment]
We actually have been running into the same issue. The problem column was `test_results_query`.

```
dbt version: 1.7.16
dbt-redshift: 1.7.6
elementary dbt-package: 0.15.2
```
