### ISSUE TITLE
Provides dbt metrics on Elementary's models

### ISSUE THREAD

**Issue by yu-iskw** [elementary-data/dbt-data-reliability#654]
## Motivation

The dbt Package creates dbt models as [model_run_results.sql
](https://github.com/elementary-data/dbt-data-reliability/blob/master/models/edr/run_results/model_run_results.sql). If the dbt Package provides dbt-metrics to analyze the created models, people who manage dbt projects in organizations can analyze with their metrics with their own data analytics tools.

https://docs.getdbt.com/docs/build/build-metrics-intro

**Comment by haritamar** [comment]
Hi @yu-iskw !
Thanks for opening this issue and sorry about the super late response.

I'm not sure if this issue is still relevant, but if so - would you mind opening a new issue in the [main Elementary repo](https://github.com/elementary-data/elementary/issues)?
Ideally with some more details about your use case.

Closing this issue for now.

Thanks,
Itamar
